# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-22 05:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0003_maindescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('categorieId', models.CharField(max_length=20)),
                ('sort', models.CharField(max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'categoriegroups',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='ChildGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('sort', models.CharField(max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axf.CategorieGroup')),
            ],
            options={
                'db_table': 'childgroups',
                'ordering': ['sort'],
            },
        ),
    ]
