# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-23 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0004_categoriegroup_childgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sex', models.BooleanField()),
                ('phoneNum', models.CharField(max_length=20)),
                ('postCode', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=500)),
                ('province', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('county', models.CharField(max_length=40)),
                ('street', models.CharField(max_length=40)),
                ('detailAddress', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('phoneNum', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('passwd', models.CharField(default=None, max_length=20, null=True)),
                ('tokenValue', models.CharField(max_length=100)),
                ('headImg', models.CharField(max_length=200)),
                ('integral', models.IntegerField(default=0)),
                ('vipLevel', models.IntegerField(default=0)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('lastLoginTime', models.DateTimeField(auto_now=True)),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axf.User'),
        ),
    ]
